### ISSUE TITLE
Cannot download released package

### ISSUE THREAD

**Issue by DinkoMiletic** [atlassian/nucleus#29]
Hello,

I am running nucleus locally for testing purpose.
When i click on released package and then on specific package build it redirects me too http://localhost:9999/project-name/7beb2bbf4fa70dba4651fd512610eb5d/linux/x64/project-name-electron_1.0.1_amd64.deb showing 404 Not found. There is no any log in terminal. 

Node: 8.11.1
Yarn: 1.6.0
Linux: Ubuntu 16.04

EDIT: Added slash, it was a bad copy

**Comment by MarshallOfSound** [comment]
@DinkoMiletic What version of Nucleus are you running and have you made any modifications, it looks like the URL you provided is invalid and couldn't have been generated by Nucleus (it's missing a slash between `project-name` and `7beb`

**Comment by DinkoMiletic** [comment]
I am using one from `master` branch.

I only modified `config.js`. Here is the content

```
const path = require('path');

module.exports = {
  /**
   * The port to run Nucleus Server on, if the port is in use the server will not start
   */
  port: 3030,

  /**
   * The fully qualified domain + path that Nucleus is being hosted at
   */
  baseURL: 'http://localhost:8888',

  /**
   * The data store to use when persisting plugins and versions.  Current possible values
   * are "sequelize", ensure you also supply valid connection details for your
   * chosen strategy below.
   * 
   * PR's welcome to add another data store.
   */
  dbStrategy: 'sequelize',

  /**
   * Sequelize connection information, please note all options are required
   * 
   * database: The name of the database to connect to
   * dialect: The type of SQL database this is, check sequelize docs for more info
   * username: Username to use when connecting
   * password; Password to use when connecting
   * host: Hostname of database
   * port: Port to use when connecting
   * storage: Path to sqlite file, only used for sqlite dialect
   */
  sequelize: {
    dialect: 'sqlite',
    storage: path.resolve(__dirname, 'db.sqlite'),
  },

  /**
   * The file store to use when persisting update files and metadata.  Current possible
   * values are "s3" and "local" ensure you also supply valid connection details if
   * required for your chosen strategy below.
   * 
   * PR's welcome to add another file store.
   */
  fileStrategy: 'local',

  /**
   * Local file configuration
   * 
   * root: Path on disk to the root of the static file store
   * staticUrl: The HTTP url to use to access the static file store remotely
   */
  local: {
    root: path.resolve(__dirname, '.files'),
    staticUrl: 'http://localhost:9999'
  },

  /**
   * There is actually no authentication config for s3, all config must be done through the standard AWS
   * environment variables or through EC2 IAM roles.
   * 
   * See http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html
   * 
   * Bucket / Region / CloudFront config goes here though
   */
  s3: {
    bucketName: '', // The name for your S3 Bucket

    cloudfront: { // If you don't have CloudFront set up and just want to use the S3 bucket set this to "null
      distributionId: '', // The CloudFront distribution ID, used for invalidating files
      publicUrl: '', // Fully qualified URL for the root of the CloudFront proxy for the S3 bucket
    }
  },

  /**
   * The authentication strategy to use when logging users in.  Current possible values are "local",
   * "openid" and "github".  Make you also supply the required authentication details 
   */
  authStrategy: 'local',

  /**
   * Local authentication details
   * 
   * The `adminIdentifiers` array should be a list of usernames
   * 
   * DISCLAIMER: This strategy should ONLY be used for local development and NEVER
   * used in production.  Unicorns cry every time this setting is used in production.
   * Don't make the unicorns cry.
   * 
   * displayName: The user friendly name of this user
   * username: A unique identifier to use when this user signs in, please note uniqueness is
   *           not enforced
   * password: Well, uhhh, their password
   * photo: A URL for their profile, entirely optional, just makes things look nicer ;)
   */
  localAuth: [{
    displayName: 'Charlie',
    username: 'charlie',
    password: 'charlie',
    photo: 'https://pbs.twimg.com/profile_images/1219364727/charlie-support_400x400.png'
  }],

  /**
   * OpenID authentication details
   * 
   * The `adminIdentifiers` array should be a list of email
   * addresses for users to consider admins
   * 
   * realm: The domain that the server is hosted on
   * stateless: Stateless mode for openID
   * profile: Whether to fetch profile information, should normally be true 
   * providerURL: Your openID provider URL
   * domain: Domain to restrict email addresses to
   */
  openid: {
    realm: 'http://localhost:8888',
    stateless: true,
    profile: true,
    providerURL: 'https://auth.myservice.com/openid/v2/op',
    domain: 'myservice.com'
  },

  /**
   * GitHub authentication details
   * 
   * The `adminIdentifiers` array should be a list of GitHub usernames
   * to consider admins
   * 
   * clientID: GitHub API client ID
   * clientSecret: GitHub API clientSecret
   * realm: The domain the server is hosted on
   */
  github: {
    clientID: '',
    clientSecret: ''
  },

  /**
   * See the documentation for your authentication strategy for what this array does
   */
  adminIdentifiers: ['admin@yourdomain.com', 'charlie'],

  /**
   * Session options, in development just leave this as default.
   * 
   * IN PRODUCTION PLEASE USE REDIS!
   * 
   * type: Can be either "redis" or null
   * 
   * redis:
   *   host: The host URL for the redis instance
   *   port: The port for the redis instance
   */
  sessionConfig: {
    type: null,
    secret: 'ThisIsNotSecret',

    redis: {
      host: '',
      port: ''
    }
  },

  organization: 'NSoft',

  /**
   * GPG key to use when signing APT and YUM releases
   * 
   * Requires to be unlocked (no password) and have both the private and
   * public key.
   */
  gpgSigningKey: ''
};`
```

**Comment by MarshallOfSound** [comment]
Can you run `tree .files` in the root directory of nucleus 👍

**Comment by DinkoMiletic** [comment]
I can debug too just tell me where is logic/route for fetching file.

```
➜  nucleus git:(master) ✗ tree .files
.files
├── public.key
└── project-name
    ├── 7beb2bbf4fa70dba4651fd512610eb5d
    │   └── versions.json
    ├── icon.ico
    ├── icon.png
    └── temp
        ├── 38678113751a41278fb5d18f337c748d
        │   └── project-name-electron_1.0.2_amd64.deb
        ├── 5a10529ea4e4265842e6942d39984e28
        │   └── project-name-electron_1.0.3_amd64.deb
        ├── 8ef0ce792ef1090611da5f282c109a69
        │   └── project-name-electron_1.0.5_amd64.deb
        ├── bb15eaa132b38d228000f62d4205df43
        │   └── project-name-electron_1.0.1_amd64.deb
        └── e7268d188af39deecad4db026bb9e3cb
            └── project-name-electron_1.0.4_amd64.deb

8 directories, 9 files
```
versions.json
```
[
  {
    "name": "1.0.1",
    "dead": false,
    "rollout": 100,
    "files": [
      {
        "fileName": "project-name-electron_1.0.1_amd64.deb",
        "arch": "x64",
        "platform": "linux",
        "type": "installer"
      }
    ]
  },
  {
    "name": "1.0.2",
    "dead": false,
    "rollout": 100,
    "files": [
      {
        "fileName": "project-name-electron-electron_1.0.2_amd64.deb",
        "arch": "x64",
        "platform": "linux",
        "type": "installer"
      }
    ]
  },
  {
    "name": "1.0.3",
    "dead": false,
    "rollout": 100,
    "files": [
      {
        "fileName": "project-name-electron_1.0.3_amd64.deb",
        "arch": "x64",
        "platform": "linux",
        "type": "installer"
      }
    ]
  },
  {
    "name": "1.0.4",
    "dead": false,
    "rollout": 100,
    "files": [
      {
        "fileName": "project-name-electron_1.0.4_amd64.deb",
        "arch": "x64",
        "platform": "linux",
        "type": "installer"
      }
    ]
  },
  {
    "name": "1.0.5",
    "dead": false,
    "rollout": 100,
    "files": [
      {
        "fileName": "project-name-electron_1.0.5_amd64.deb",
        "arch": "x64",
        "platform": "linux",
        "type": "installer"
      }
    ]
  }
]
```

**Comment by DinkoMiletic** [comment]
```
nucleus:rest Listing applications +11s
nucleus:positioner Saving temporary file: 765599207a863184c381230fea6ebbcb/project-name-electron_1.0.6_amd64.deb for app: project-name +1s
(node:3899) Warning: Use Cipheriv for counter mode of aes-256-ctr
nucleus:rest Fetching temporary releases for app: project-name and channel: stable +499ms
nucleus:rest User: charlie promoted a temporary release for app: 'project-name' on channel: stable becomes version: 1.0.6 +36s
nucleus:rest Tested files: [project-name-electron_1.0.6_amd64.deb] but stored: [project-name-electron_1.0.6_amd64.deb] +74ms
nucleus:rest Releasing file: project-name-electron_1.0.6_amd64.deb to version: 1.0.6 for (project-name/stable) +1ms
nucleus:positioner Fetching temporary file: 765599207a863184c381230fea6ebbcb/project-name-electron_1.0.6_amd64.deb for app: project-name +0ms
nucleus:positioner Handling upload (project-name-electron_1.0.6_amd64.deb) for app (project-name) and channel (stable) for version (1.0.6) on platform/arch (linux/x64) +91ms
nucleus:positioner Adding deb file to apt repo +0ms
nucleus:rest Unhandled error: /1/channel/7beb2bbf4fa70dba4651fd512610eb5d/temporary_releases/8/release +627ms
nucleus:rest ChildProcessError: `gpg --import /tmp/nucleus-wd-F3ctPy/key.asc` failed with code 2
nucleus:rest     at ChildProcess.<anonymous> (/home/dinko/public_html/nucleus/node_modules/child-process-promise/lib/index.js:132:23)
nucleus:rest     at emitTwo (events.js:126:13)
nucleus:rest     at ChildProcess.emit (events.js:214:7)
nucleus:rest     at maybeClose (internal/child_process.js:925:16)
nucleus:rest     at Socket.stream.socket.on (internal/child_process.js:346:11)
nucleus:rest     at emitOne (events.js:116:13)
nucleus:rest     at Socket.emit (events.js:211:7)
nucleus:rest     at Pipe._handle.close [as _onclose] (net.js:567:12) +0ms
nucleus:rest Fetching temporary releases for app: project-name and channel: stable +40ms
nucleus:rest Listing applications +30ms
```
and files:

```
.files
├── public.key
└── project-name
    ├── 7beb2bbf4fa70dba4651fd512610eb5d
    │   └── versions.json
    ├── icon.ico
    ├── icon.png
    └── temp
        ├── 38678113751a41278fb5d18f337c748d
        │   └── project-name-electron_1.0.2_amd64.deb
        ├── 5a10529ea4e4265842e6942d39984e28
        │   └── project-name-electron_1.0.3_amd64.deb
        ├── 765599207a863184c381230fea6ebbcb
        │   └── project-name-electron_1.0.6_amd64.deb
        ├── 8ef0ce792ef1090611da5f282c109a69
        │   └── project-name-electron_1.0.5_amd64.deb
        ├── bb15eaa132b38d228000f62d4205df43
        │   └── project-name-electron_1.0.1_amd64.deb
        └── e7268d188af39deecad4db026bb9e3cb
            └── project-name-electron_1.0.4_amd64.deb
```

**Comment by MarshallOfSound** [comment]
@DinkoMiletic There ya go, looks like you either haven't provided a GPG key, or that GPG key is invalid so when it tried to generate the apt repo it failed.  Provide a valid GPG key and everything should start working, I'll raise an issue to provide better error handling in this case 👍

**Comment by DinkoMiletic** [comment]
Great :) 

Thanks a lot

**Comment by MarshallOfSound** [comment]
Fixed in 5a8432b939a712bff1acaa3353998a6bf175de7e

**Comment by bastientanesie** [comment]
I stumbled upon this issue because I had some 404 errors too. It turned out that it was cause by the fact that I didn't have any "stable" version yet.  
@MarshallOfSound Maybe it should be pointed out somewhere that it's needed to have at least one stable version for the `autoUpdater` to work properly?

**Comment by MarshallOfSound** [comment]
@bastientanesie Hm, where would that messaging go?  It can't go in the 404 or it might break stuff and the web UI is already a bit cluttered.  Open to suggestions to surface that issue easier though

**Comment by bastientanesie** [comment]
Maybe we can put some warning message in this box, after the "no released version" message?
![image](https://user-images.githubusercontent.com/1671498/40229200-d41802ac-5a93-11e8-92c0-63aa8773c4cb.png)
I think it'd be a pretty good place for that kind of warning.

**Comment by MarshallOfSound** [comment]
@DinkoMiletic I believe the frontend attempts to download the wrong path for linux files, I was looking at something similar this morning.

As for your error, please ensure you have installed all the system requirements:

https://github.com/atlassian/nucleus#system-requirements
