### ISSUE TITLE
Bug using forever for "npm start" due by missing config.js

### ISSUE THREAD

**Issue by baxtheman** [atlassian/nucleus#49]
Using start.sh, the line `forever start -c “npm start” ./ ` cause this error:

```
> nucleus-server@1.1.1 start /home/rpaubuntu/work/nucleus
> npm run start-server "./" "./"


> nucleus-server@1.1.1 start-server /home/rpaubuntu/work/nucleus
> node lib/index.js "./" "./"

/home/rpaubuntu/work/nucleus/lib/rest/auth.js:27
    secret: config_1.sessionConfig.secret,
                                   ^

TypeError: Cannot read property 'secret' of undefined
    at Object.<anonymous> (/home/rpaubuntu/work/nucleus/lib/rest/auth.js:27:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rpaubuntu/work/nucleus/lib/index.js:26:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
```

We suggest this solution (after that fix you have to run `yarn build` to generate js) :

```
src/config.ts
line 13
-- if (!config) {
++ if (!config || !config.port) {
```

bye

**Comment by MarshallOfSound** [comment]
Merging into #44
