### ISSUE TITLE
Nucleus does not handle delta publish artifacts from electron-forge

### ISSUE THREAD

**Issue by b-zurg** [atlassian/nucleus#89]
I'm trying to configure electron-forge to upload artifacts to nucleus as it seems like a great solution, however every time I try to release a set of release artifacts I encounter a problem.

The delta updates are being built and uploaded fine but when releasing the following output is shown:

```
nucleus_1  | Mon, 11 May 2020 08:09:10 GMT nucleus:rest TypeError: Cannot read property 'toUpperCase' of null
nucleus_1  |     at Object.<anonymous> (/opt/service/lib/files/utils/win32.js:25:44)
nucleus_1  |     at Generator.next (<anonymous>)
nucleus_1  |     at fulfilled (/opt/service/lib/files/utils/win32.js:4:58)
nucleus_1  |     at <anonymous>
nucleus_1  | Mon, 11 May 2020 08:09:10 GMT nucleus:rest Fetching temporary releases for app: brl and channel: Stable
nucleus_1  | Mon, 11 May 2020 08:09:10 GMT nucleus:rest Listing applications
```

The property that it's talking about is the `sha1` property. I desperately want to use nucleus but if delta updates are not working then that's a hard pill to swallow.

Interestingly enough updates are all good when not doing delta updates and just uploading 2 full packages.

**Comment by psamim** [comment]
Too sad.

**Comment by b-zurg** [comment]
> Too sad.

Are you experiencing the same thing?

**Comment by psamim** [comment]
@b-zurg Yes.

**Comment by b-zurg** [comment]
I think nucleus is pretty viable if you can stomach not having Delta updates. Otherwise the differential updates that electron-builder has works pretty well as and is even more efficient than squirrel's delta updates.

**Comment by psamim** [comment]
@b-zurg Dear Buzurg! I tried to setup publishing with electron-builder but failed, as I was confused by the its docs but forge and nucleus combination was so straight forward and easy. Are you referring to the nsis format? Also I would really appreciate it if you could point me to an example repo or something.

**Comment by TomaterID** [comment]
Guys, I nailed down this problem in the code with this, and few others too. Working on patch right now. Unfortunately, there is no point to push PR for that, as no one is reviewing them. If someone interested - fixes will be in my fork of the repo. I also think about doing some UI improvements too. Currently it is not very convenient.
