### ISSUE TITLE
error E:\User\Documents\Work\nucleus-server\node_modules\sqlite3: Command failed.

### ISSUE THREAD

**Issue by clark-97** [atlassian/nucleus#98]
install nucleus manually, when I run `yarn` then get those errors. any helps? thanks :)
```sh
PS E:\User\Documents\Work\nucleus-server> node --version
v14.4.0
PS E:\User\Documents\Work\nucleus-server> npm --version
6.14.5
PS E:\User\Documents\Work\nucleus-server> yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @atlaskit/banner@6.1.2" has incorrect peer dependency "react@^16.3.0".
warning " > @atlaskit/banner@6.1.2" has incorrect peer dependency "styled-components@^3.2.6".       
warning "@atlaskit/banner > @atlaskit/theme@4.1.0" has incorrect peer dependency "react@^16.3.0".   
warning "@atlaskit/banner > @atlaskit/theme@4.1.0" has incorrect peer dependency "styled-components@^3.2.6".
[4/4] Building fresh packages...
[1/4] ⠁ sqlite3
[-/4] ⠁ waiting...
[-/4] ⠁ waiting...
error E:\User\Documents\Work\nucleus-server\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: E:\User\Documents\Work\nucleus-server\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@14.4.0 | win32 | x64
node-pre-gyp info check checked for "E:\User\Documents\Work\nucleus-server\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v83-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@14.4.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@14.4.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gyp info it worked if it ends with ok
gypgyp info using node-gyp@3.6.2
gyp info  info usingit worked if it ends with ok
 node@14.4.0 | win32 | x64
gyp info using node-gyp@3.6.2
gyp info using node@14.4.0 | win32 | x64
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.4.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.4.0 | win32 | x64
gyp info spawn C:\Users\Clark\.windows-build-tools\python27\python.EXE
gyp info spawn args [
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Clark\\.node-gyp\\14.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Clark\\.node-gyp\\14.4.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Clark\\.node-gyp\\14.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3\\build',    
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Users\Clark\.windows-build-tools\python27\python.EXE
gyp info spawn args [
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Clark\\.node-gyp\\14.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Clark\\.node-gyp\\14.4.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Clark\\.node-gyp\\14.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3\\build',    
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.4.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@14.4.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" 
switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" 
switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [E:\User\Documents\Work\nucleus-server\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [E:\User\Documents\Work\nucleus-server\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\User\Documents\Work\nucleus-server\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)        
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node" 
"--module_name=node_sqlite3" "--module_path=E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64"
gyp ERR! cwd E:\User\Documents\Work\nucleus-server\node_modules\sqlite3
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\User\Documents\Work\nucleus-server\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\User\Documents\Work\nucleus-server\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\User\Documents\Work\nucleus-server\node_modules\sqlite3\lib\binding\node-v83-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\User\Documents\Work\nucleus-server\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\User\\Documents\\Work\\nucleus-server\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\User\Documents\Work\nucleus-server\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\User\Documents\Work\nucleus-server\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\User\Documents\Work\nucleus-server\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --


```

**Comment by b-zurg** [comment]
I believe nucleus has deps that depends on a lower version of node (8 I believe)

**Comment by clark-97** [comment]
> I believe nucleus has deps that depends on a lower version of node (8 I believe)

so should I install node 8 first? @b-zurg

**Comment by b-zurg** [comment]
Yes, give that a try

**Comment by clark-97** [comment]
I installed nvm and change node version to 8.4.0, `yarn` is okay, but `yarn dev` not.
```sh
PS E:\User\Documents\Work\nucleus-server> yarn
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.97s.
PS E:\User\Documents\Work\nucleus-server> yarn dev
yarn run v1.22.4
$ concurrently --raw "npm run start:fe" "npm run start:server:dev" "npm run start:static"

> nucleus-server@1.1.3 start:fe E:\User\Documents\Work\nucleus-server
> webpack-dev-server --progress --profile --colors --quiet --open


> nucleus-server@1.1.3 start:server:dev E:\User\Documents\Work\nucleus-server
> nodemon --watch src --exec "npm run build:server && cross-env DEBUG=nucleus* npm run start:server:prod" -e ts


> nucleus-server@1.1.3 start:static E:\User\Documents\Work\nucleus-server
> make-dir .files && serve .files --port 9999 --silent

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: E:\User\Documents\Work\nucleus-server\src/**/*
[nodemon] starting `npm run build:server && cross-env DEBUG=nucleus* npm run start:server:prod`     

> nucleus-server@1.1.3 build:server E:\User\Documents\Work\nucleus-server
> tsc && rm -rf lib/__spec__ lib/**/__spec__

 10% building modules 2/4 modules 2 active ...\webpack\hot nonrecursive /^\.\/log$/
> nucleus-server@1.1.3 start:server:prod E:\User\Documents\Work\nucleus-server
> node lib/index.js

 11% building modules 9/10 modules 1 active ...\Work\nucleus-server\public\index.tsx
[at-loader] Using typescript@3.1.6 from typescript and "tsconfig.json" from E:\User\Documents\Work\nucleus-server\tsconfig.public.json.

  nucleus Setting up server +0ms
  nucleus Connecting to DB +3ms
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators 
node_modules\sequelize\lib\sequelize.js:236:13
  nucleus Checking GPG key +2s
"--gpg: directory '/c/Users/Clark/.gnupg' created\ngpg: keybox '/c/Users/Clark/.gnupg/pubring.kbx' created\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\n"
  nucleus Bad gpg key, invalid +432ms
GPG key is invalid or missing, you must provide "config.gpgSigningKey"
 11% building modules 10/10 modules 0 activenpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nucleus-server@1.1.3 start:server:prod: `node lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nucleus-server@1.1.3 start:server:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Clark\AppData\Roaming\npm-cache\_logs\2020-07-01T07_03_22_444Z-debug.log
 11% building modules 10/11 modules 1 active ...ode_modules\webpack\buildin\module.js[nodemon] app crashed - waiting for file changes before starting...
50309ms building modules                                                                
71ms sealing
16ms optimizing
1ms basic module optimization
14ms module optimization
2ms advanced module optimization
3ms basic chunk optimization
11ms chunk optimization
3ms advanced chunk optimization
2ms module and chunk tree optimization
31ms module reviving
6ms module order optimization
10ms module id optimization
7ms chunk reviving 
9ms chunk order optimization
61ms chunk id optimization
67ms hashing
47ms module assets processing
2694ms chunk assets processing
47ms additional chunk assets processing
1ms recording
1ms additional asset processing
13ms chunk asset optimization
260ms asset optimization
241ms emitting
[HPM] Error occurred while trying to proxy request /rest/config from 127.0.0.1:8888 to http://localhost:3030 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

```

**Comment by clark-97** [comment]
okay, I should add gpg into config.js
https://github.com/atlassian/nucleus/issues/37#issuecomment-391399362

**Comment by b-zurg** [comment]
Oh yeah. Honestly there should be an error message for that. It's so cryptic. 

I also kind of just use the docker image as I think there's certain deps that don't even build on later versions of Ubuntu for example.

It's a solid protect but could use a refresh

**Comment by clark-97** [comment]
can I use nucleus as a nodejs module? but how? @b-zurg

**Comment by b-zurg** [comment]
Do you have the option to run it as a docker container?  That might be your fastest option. I haven't run nucleus on a non-docker environment for a little while. 

It's definitely possible but the dependencies really need to be upgraded.

**Comment by busterbogheart** [comment]
@b-zurg @clark-97 So is it currently possible to run locally?
